"""remove_ip_address_field_from_servers

Revision ID: 1d0d6eb79a02
Revises: 8c6861bd13aa
Create Date: 2025-07-19 20:09:35.353602

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1d0d6eb79a02'
down_revision: Union[str, Sequence[str], None] = '8c6861bd13aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
